export type CuratedBook = {
  ol_key: string       // e.g. 'OL82563W' (slug form, no /works/ prefix)
  title: string
  author: string
  isbn: string         // used for cover: covers.openlibrary.org/b/isbn/{isbn}-M.jpg
  genre: string
  year: number
  description: string
}

export const CURATED_BOOKS: CuratedBook[] = [
  // ── Fantasy ──────────────────────────────────────────────────────────────
  {
    ol_key: 'OL82563W',
    title: "Harry Potter and the Philosopher's Stone",
    author: 'J.K. Rowling',
    isbn: '9780439708180',
    genre: 'Fantasy',
    year: 1997,
    description: 'An orphan boy discovers he is a wizard and enters the magical world of Hogwarts.',
  },
  {
    ol_key: 'OL27516W',
    title: 'The Fellowship of the Ring',
    author: 'J.R.R. Tolkien',
    isbn: '9780618346257',
    genre: 'Fantasy',
    year: 1954,
    description: 'A young hobbit is entrusted with a powerful ring that must be destroyed before dark forces claim it.',
  },
  {
    ol_key: 'OL30358W',
    title: 'The Hobbit',
    author: 'J.R.R. Tolkien',
    isbn: '9780261102217',
    genre: 'Fantasy',
    year: 1937,
    description: 'Bilbo Baggins is swept into an epic quest to reclaim a lost dwarven kingdom from a fearsome dragon.',
  },
  {
    ol_key: 'OL102749W',
    title: 'Dune',
    author: 'Frank Herbert',
    isbn: '9780441013593',
    genre: 'Fantasy',
    year: 1965,
    description: 'A young nobleman navigates the deadly politics and ecology of the desert planet Arrakis.',
  },
  {
    ol_key: 'OL27482W',
    title: 'A Game of Thrones',
    author: 'George R.R. Martin',
    isbn: '9780553381689',
    genre: 'Fantasy',
    year: 1996,
    description: 'Noble families fight for control of Westeros while an ancient enemy stirs beyond the northern wall.',
  },
  {
    ol_key: 'OL8454038W',
    title: 'The Name of the Wind',
    author: 'Patrick Rothfuss',
    isbn: '9780756404741',
    genre: 'Fantasy',
    year: 2007,
    description: 'A legendary wizard recounts his rise from a homeless orphan to the most feared figure of his age.',
  },
  {
    ol_key: 'OL1960111W',
    title: 'Mistborn: The Final Empire',
    author: 'Brandon Sanderson',
    isbn: '9780765311788',
    genre: 'Fantasy',
    year: 2006,
    description: 'A band of rebels plot to overthrow an immortal dark lord who has ruled for a thousand years.',
  },
  {
    ol_key: 'OL1011484W',
    title: 'American Gods',
    author: 'Neil Gaiman',
    isbn: '9780380789030',
    genre: 'Fantasy',
    year: 2001,
    description: 'A man is drawn into a war between old gods and new gods in a mythic American road story.',
  },

  // ── Classics ─────────────────────────────────────────────────────────────
  {
    ol_key: 'OL1168007W',
    title: '1984',
    author: 'George Orwell',
    isbn: '9780451524935',
    genre: 'Classics',
    year: 1949,
    description: 'A man living in a totalitarian surveillance state risks everything for truth and love.',
  },
  {
    ol_key: 'OL3435529W',
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    isbn: '9780061743528',
    genre: 'Classics',
    year: 1960,
    description: 'A lawyer defends an innocent Black man in the Deep South as seen through his young daughter\'s eyes.',
  },
  {
    ol_key: 'OL1394865W',
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    isbn: '9780141439518',
    genre: 'Classics',
    year: 1813,
    description: 'Elizabeth Bennet navigates love, class, and social expectations in Regency-era England.',
  },
  {
    ol_key: 'OL468431W',
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    isbn: '9780743273565',
    genre: 'Classics',
    year: 1925,
    description: 'A mysterious millionaire pursues an idealized dream in the glittering excess of the Jazz Age.',
  },
  {
    ol_key: 'OL10233W',
    title: 'Brave New World',
    author: 'Aldous Huxley',
    isbn: '9780060850524',
    genre: 'Classics',
    year: 1932,
    description: 'A genetically engineered utopia raises questions about freedom, identity, and what it means to be human.',
  },
  {
    ol_key: 'OL26431W',
    title: 'Lord of the Flies',
    author: 'William Golding',
    isbn: '9780571295715',
    genre: 'Classics',
    year: 1954,
    description: 'Stranded boys create their own society on a deserted island, with terrifying results.',
  },
  {
    ol_key: 'OL48462W',
    title: 'Jane Eyre',
    author: 'Charlotte Brontë',
    isbn: '9780141441146',
    genre: 'Classics',
    year: 1847,
    description: 'An orphaned governess falls for her brooding employer while uncovering the dark secrets of Thornfield Hall.',
  },
  {
    ol_key: 'OL29374W',
    title: 'Crime and Punishment',
    author: 'Fyodor Dostoevsky',
    isbn: '9780140449136',
    genre: 'Classics',
    year: 1866,
    description: 'A destitute student commits a murder and then wrestles with guilt, morality, and redemption.',
  },

  // ── Science Fiction ───────────────────────────────────────────────────────
  {
    ol_key: 'OL17356629W',
    title: 'The Martian',
    author: 'Andy Weir',
    isbn: '9780553418026',
    genre: 'Science Fiction',
    year: 2011,
    description: 'An astronaut stranded alone on Mars must survive using science, ingenuity, and dark humor.',
  },
  {
    ol_key: 'OL24182680W',
    title: 'Project Hail Mary',
    author: 'Andy Weir',
    isbn: '9780593135204',
    genre: 'Science Fiction',
    year: 2021,
    description: 'A lone astronaut wakes with no memory, billions of miles from home, on a mission to save Earth.',
  },
  {
    ol_key: 'OL460952W',
    title: "Ender's Game",
    author: 'Orson Scott Card',
    isbn: '9780812550702',
    genre: 'Science Fiction',
    year: 1985,
    description: "A child military genius is trained at a brutal battle school to lead humanity's defense against aliens.",
  },
  {
    ol_key: 'OL297060W',
    title: "The Hitchhiker's Guide to the Galaxy",
    author: 'Douglas Adams',
    isbn: '9780345391803',
    genre: 'Science Fiction',
    year: 1979,
    description: 'An ordinary Englishman is dragged into the absurd cosmos just as Earth is demolished for a bypass.',
  },
  {
    ol_key: 'OL47509W',
    title: 'Neuromancer',
    author: 'William Gibson',
    isbn: '9780441569595',
    genre: 'Science Fiction',
    year: 1984,
    description: 'A washed-up hacker is hired for one last heist in a neon-drenched future of cyberspace and conspiracy.',
  },
  {
    ol_key: 'OL7586604W',
    title: 'The Hunger Games',
    author: 'Suzanne Collins',
    isbn: '9780439023481',
    genre: 'Science Fiction',
    year: 2008,
    description: 'A girl volunteers to fight to the death on live television to save her younger sister.',
  },

  // ── Contemporary Fiction ──────────────────────────────────────────────────
  {
    ol_key: 'OL7353064W',
    title: 'The Kite Runner',
    author: 'Khaled Hosseini',
    isbn: '9781594631931',
    genre: 'Contemporary',
    year: 2003,
    description: 'A man returns to Taliban-ruled Afghanistan to make amends for a childhood betrayal.',
  },
  {
    ol_key: 'OL2614621W',
    title: 'Norwegian Wood',
    author: 'Haruki Murakami',
    isbn: '9780375704024',
    genre: 'Contemporary',
    year: 1987,
    description: 'A college student in 1960s Tokyo navigates grief, memory, and first love.',
  },
  {
    ol_key: 'OL7987283W',
    title: 'The Alchemist',
    author: 'Paulo Coelho',
    isbn: '9780062315007',
    genre: 'Contemporary',
    year: 1988,
    description: 'A shepherd boy travels from Spain to Egypt following his dream, guided by the language of the world.',
  },
  {
    ol_key: 'OL15980490W',
    title: 'The Night Circus',
    author: 'Erin Morgenstern',
    isbn: '9780307744432',
    genre: 'Contemporary',
    year: 2011,
    description: 'Two young magicians are pitted against each other in a duel played out inside an enchanted black-and-white circus.',
  },
  {
    ol_key: 'OL19685044W',
    title: 'Where the Crawdads Sing',
    author: 'Delia Owens',
    isbn: '9780735224292',
    genre: 'Contemporary',
    year: 2018,
    description: 'A girl raised alone in the North Carolina marshes becomes entangled in a murder mystery.',
  },
  {
    ol_key: 'OL17938416W',
    title: 'Circe',
    author: 'Madeline Miller',
    isbn: '9780316556347',
    genre: 'Contemporary',
    year: 2018,
    description: 'The legendary witch of Greek mythology discovers her own power and identity among gods and mortals.',
  },
  {
    ol_key: 'OL17788296W',
    title: 'The Seven Husbands of Evelyn Hugo',
    author: 'Taylor Jenkins Reid',
    isbn: '9781501161925',
    genre: 'Contemporary',
    year: 2017,
    description: 'A reclusive Hollywood icon finally tells the scandalous truth of her glamorous, ruthless life.',
  },
  {
    ol_key: 'OL19734434W',
    title: 'Eleanor Oliphant is Completely Fine',
    author: 'Gail Honeyman',
    isbn: '9780735220683',
    genre: 'Contemporary',
    year: 2017,
    description: 'A deeply lonely woman with a painful past finds an unlikely path toward connection and healing.',
  },

  // ── Mystery & Thriller ────────────────────────────────────────────────────
  {
    ol_key: 'OL49571W',
    title: 'And Then There Were None',
    author: 'Agatha Christie',
    isbn: '9780062073488',
    genre: 'Mystery',
    year: 1939,
    description: 'Ten strangers lured to a remote island are killed one by one according to a nursery rhyme.',
  },
  {
    ol_key: 'OL9296688W',
    title: 'The Girl with the Dragon Tattoo',
    author: 'Stieg Larsson',
    isbn: '9780307454546',
    genre: 'Mystery',
    year: 2005,
    description: 'A disgraced journalist and a brilliant hacker investigate a decades-old disappearance in a wealthy Swedish family.',
  },
  {
    ol_key: 'OL15532875W',
    title: 'Gone Girl',
    author: 'Gillian Flynn',
    isbn: '9780307588371',
    genre: 'Mystery',
    year: 2012,
    description: 'On their anniversary, a man\'s wife vanishes and the clues paint an unsettling portrait of their marriage.',
  },
  {
    ol_key: 'OL17793127W',
    title: 'Big Little Lies',
    author: 'Liane Moriarty',
    isbn: '9780399167065',
    genre: 'Mystery',
    year: 2014,
    description: 'Three women\'s seemingly perfect lives unravel around a school-gate incident with lethal consequences.',
  },
  {
    ol_key: 'OL17978698W',
    title: 'The Da Vinci Code',
    author: 'Dan Brown',
    isbn: '9780385504201',
    genre: 'Mystery',
    year: 2003,
    description: 'A Harvard professor races through Europe uncovering a centuries-old religious conspiracy.',
  },
  {
    ol_key: 'OL9694438W',
    title: 'In the Woods',
    author: 'Tana French',
    isbn: '9780143113492',
    genre: 'Mystery',
    year: 2007,
    description: 'A Dublin detective investigates a murder near the woods where, as a child, he was the only survivor.',
  },

  // ── Romance ───────────────────────────────────────────────────────────────
  {
    ol_key: 'OL16828938W',
    title: 'The Fault in Our Stars',
    author: 'John Green',
    isbn: '9780525478812',
    genre: 'Romance',
    year: 2012,
    description: 'Two teenagers with cancer fall in love and travel to Amsterdam in search of a reclusive author.',
  },
  {
    ol_key: 'OL19717167W',
    title: 'It Ends with Us',
    author: 'Colleen Hoover',
    isbn: '9781501110368',
    genre: 'Romance',
    year: 2016,
    description: 'A young woman must make an impossible choice between the man she loves and her own safety.',
  },
  {
    ol_key: 'OL462674W',
    title: 'Outlander',
    author: 'Diana Gabaldon',
    isbn: '9780440212560',
    genre: 'Romance',
    year: 1991,
    description: 'A WWII nurse is hurled back to 18th-century Scotland where she falls in love and must survive.',
  },
  {
    ol_key: 'OL19671064W',
    title: 'The Hating Game',
    author: 'Sally Thorne',
    isbn: '9780062439598',
    genre: 'Romance',
    year: 2016,
    description: 'Two executive assistants locked in a bitter rivalry discover their hate might be something else entirely.',
  },

  // ── Historical Fiction ────────────────────────────────────────────────────
  {
    ol_key: 'OL17153823W',
    title: 'All the Light We Cannot See',
    author: 'Anthony Doerr',
    isbn: '9781476746586',
    genre: 'Historical Fiction',
    year: 2014,
    description: 'The lives of a blind French girl and a German orphan converge in occupied France during WWII.',
  },
  {
    ol_key: 'OL8145660W',
    title: 'The Book Thief',
    author: 'Markus Zusak',
    isbn: '9780375842207',
    genre: 'Historical Fiction',
    year: 2005,
    description: 'A young girl steals books during WWII Germany, narrated by Death, who watches her story with wonder.',
  },
  {
    ol_key: 'OL16550W',
    title: 'The Pillars of the Earth',
    author: 'Ken Follett',
    isbn: '9780451166890',
    genre: 'Historical Fiction',
    year: 1989,
    description: 'The building of a cathedral in 12th-century England becomes the canvas for an epic tale of ambition and faith.',
  },
  {
    ol_key: 'OL17816720W',
    title: 'The Nightingale',
    author: 'Kristin Hannah',
    isbn: '9780312577223',
    genre: 'Historical Fiction',
    year: 2015,
    description: 'Two sisters in Nazi-occupied France each find their own form of courage to survive and resist.',
  },
  {
    ol_key: 'OL471252W',
    title: 'The Secret History',
    author: 'Donna Tartt',
    isbn: '9781400031702',
    genre: 'Historical Fiction',
    year: 1992,
    description: 'A group of elite classics students at a Vermont college commit a terrible act with lasting consequences.',
  },
  {
    ol_key: 'OL21117728W',
    title: 'The Song of Achilles',
    author: 'Madeline Miller',
    isbn: '9780062060624',
    genre: 'Historical Fiction',
    year: 2012,
    description: 'The Trojan War retold through the bond between Achilles and his devoted companion Patroclus.',
  },

  // ── Memoir & Non-Fiction ──────────────────────────────────────────────────
  {
    ol_key: 'OL18016432W',
    title: 'Educated',
    author: 'Tara Westover',
    isbn: '9780399590504',
    genre: 'Non-Fiction',
    year: 2018,
    description: 'A young woman raised by survivalist parents in rural Idaho educates herself into Cambridge and beyond.',
  },
  {
    ol_key: 'OL20007936W',
    title: 'Becoming',
    author: 'Michelle Obama',
    isbn: '9781524763138',
    genre: 'Non-Fiction',
    year: 2018,
    description: 'The former First Lady reflects on her roots, her journey to the White House, and her enduring hope.',
  },
  {
    ol_key: 'OL17804642W',
    title: 'Sapiens: A Brief History of Humankind',
    author: 'Yuval Noah Harari',
    isbn: '9780062316097',
    genre: 'Non-Fiction',
    year: 2011,
    description: 'A sweeping history of humanity from the Stone Age to the present, challenging everything we know about ourselves.',
  },
  {
    ol_key: 'OL20163582W',
    title: 'Atomic Habits',
    author: 'James Clear',
    isbn: '9780735211292',
    genre: 'Non-Fiction',
    year: 2018,
    description: 'A proven framework for building good habits and breaking bad ones through tiny, consistent changes.',
  },
  {
    ol_key: 'OL17034476W',
    title: 'The Body Keeps the Score',
    author: 'Bessel van der Kolk',
    isbn: '9780670785933',
    genre: 'Non-Fiction',
    year: 2014,
    description: 'A groundbreaking exploration of how trauma reshapes the body and mind — and paths to recovery.',
  },
  {
    ol_key: 'OL7981052W',
    title: "Man's Search for Meaning",
    author: 'Viktor E. Frankl',
    isbn: '9780807014295',
    genre: 'Non-Fiction',
    year: 1946,
    description: 'A psychiatrist\'s account of surviving the Holocaust and his method for finding meaning in suffering.',
  },

  // ── Young Adult ───────────────────────────────────────────────────────────
  {
    ol_key: 'OL1988153W',
    title: 'Harry Potter and the Chamber of Secrets',
    author: 'J.K. Rowling',
    isbn: '9780439064873',
    genre: 'Young Adult',
    year: 1998,
    description: 'Harry returns to Hogwarts to face a mysterious force that is petrifying students one by one.',
  },
  {
    ol_key: 'OL15983557W',
    title: 'Divergent',
    author: 'Veronica Roth',
    isbn: '9780062024039',
    genre: 'Young Adult',
    year: 2011,
    description: 'In a fractured future society, a girl discovers she doesn\'t fit any faction — and that makes her dangerous.',
  },
  {
    ol_key: 'OL14976510W',
    title: 'The Maze Runner',
    author: 'James Dashner',
    isbn: '9780385737951',
    genre: 'Young Adult',
    year: 2009,
    description: 'A boy wakes with no memory in a dangerous maze with other boys who have all forgotten who they are.',
  },
  {
    ol_key: 'OL8351962W',
    title: 'The Lightning Thief',
    author: 'Rick Riordan',
    isbn: '9780786838653',
    genre: 'Young Adult',
    year: 2005,
    description: 'A boy who learns he is the son of a Greek god goes on a quest to prevent a war among the Olympians.',
  },
  {
    ol_key: 'OL16547538W',
    title: 'The Giver',
    author: 'Lois Lowry',
    isbn: '9780440237686',
    genre: 'Young Adult',
    year: 1993,
    description: 'A boy in a seemingly perfect society is chosen to learn the truth about the world beyond their community.',
  },
  {
    ol_key: 'OL7353119W',
    title: 'Tuesdays with Morrie',
    author: 'Mitch Albom',
    isbn: '9780767905923',
    genre: 'Young Adult',
    year: 1997,
    description: 'A journalist visits his dying former professor every Tuesday to learn life\'s greatest lessons.',
  },
]

export const GENRES = [
  'Fantasy',
  'Classics',
  'Science Fiction',
  'Contemporary',
  'Mystery',
  'Romance',
  'Historical Fiction',
  'Non-Fiction',
  'Young Adult',
]

export function getBooksByGenre(genre: string): CuratedBook[] {
  return CURATED_BOOKS.filter(b => b.genre === genre)
}

export function getFeaturedBooks(count = 12): CuratedBook[] {
  // Return a mix from different genres
  const genres = GENRES
  const result: CuratedBook[] = []
  let i = 0
  while (result.length < count) {
    const genreBooks = getBooksByGenre(genres[i % genres.length])
    const book = genreBooks[Math.floor(result.length / genres.length)]
    if (book && !result.includes(book)) result.push(book)
    i++
    if (i > count * 3) break
  }
  return result.slice(0, count)
}

// Convert a CuratedBook to the OLBook shape used across the app.
// Routing uses /isbn/{isbn} so clicking a curated book always shows
// the exact correct book — no dependency on potentially wrong OL work keys.
export function curatedToOLBook(b: CuratedBook) {
  return {
    ol_key: `/isbn/${b.isbn}`,   // ISBN-based routing → 100% correct book
    title: b.title,
    author_names: [b.author],
    author_keys: [] as string[],
    cover_id: undefined as number | undefined,
    cover_isbn: b.isbn,
    description: b.description,
    genres: [b.genre],
    first_publish_year: b.year,
  }
}
